//! Example of unit-testing command handlers without a running Valkey server.
//!
//! Command functions take `&impl ContextInterface` rather than `&Context`,
//! so tests can substitute [`MockContext`] (generated by `mockall`) for the
//! real context and assert on logging and string-creation calls. See the
//! `tests` module below for the pattern.
//!
//! [`MockContext`]: valkey_module::MockContext

use valkey_module::alloc::ValkeyAlloc;
use valkey_module::logging::ValkeyLogLevel;
use valkey_module::{
    valkey_module, ContextInterface, NextArg, ValkeyResult, ValkeyString, ValkeyValue, VALKEY_OK,
};

fn mockctx_log(ctx: &impl ContextInterface, _args: Vec<ValkeyString>) -> ValkeyResult {
    ctx.log(ValkeyLogLevel::Notice, "log");
    ctx.log_notice("n");
    ctx.log_warning("w");
    ctx.log_verbose("v");
    ctx.log_debug("d");
    VALKEY_OK
}

fn mockctx_hello(ctx: &impl ContextInterface, args: Vec<ValkeyString>) -> ValkeyResult {
    let mut args = args.into_iter().skip(1);
    let name = args.next_string().unwrap_or_else(|_| "World".to_string());
    let greeting = format!("Hello, {name}!");
    let reply = ctx.create_string(greeting.as_bytes());
    Ok(ValkeyValue::BulkValkeyString(reply))
}

//////////////////////////////////////////////////////

valkey_module! {
    name: "mockctx",
    version: 1,
    allocator: (ValkeyAlloc, ValkeyAlloc),
    data_types: [],
    commands: [
        ["mockctx.log", mockctx_log, "", 0, 0, 0],
        ["mockctx.hello", mockctx_hello, "", 0, 0, 0],
    ],
}

//////////////////////////////////////////////////////

#[cfg(test)]
mod tests {
    use super::*;
    use mockall::{predicate::eq, Sequence};
    use std::str::from_utf8;
    use valkey_module::{MockContext, ValkeyError};

    fn expect_create_string(ctx: &mut MockContext, expected: &'static [u8]) {
        ctx.expect_create_string()
            .with(eq(expected))
            .times(1)
            .returning(|tmp| ValkeyString::create_for_test(from_utf8(tmp).unwrap()));
    }

    #[test]
    fn test_log() {
        let mut seq = Sequence::new();
        let mut ctx = MockContext::new();
        ctx.expect_log()
            .withf(|level, msg| matches!(level, ValkeyLogLevel::Notice) && msg == "log")
            .times(1)
            .in_sequence(&mut seq)
            .return_const(());
        ctx.expect_log_notice()
            .with(eq("n"))
            .times(1)
            .in_sequence(&mut seq)
            .return_const(());
        ctx.expect_log_warning()
            .with(eq("w"))
            .times(1)
            .in_sequence(&mut seq)
            .return_const(());
        ctx.expect_log_verbose()
            .with(eq("v"))
            .times(1)
            .in_sequence(&mut seq)
            .return_const(());
        ctx.expect_log_debug()
            .with(eq("d"))
            .times(1)
            .in_sequence(&mut seq)
            .return_const(());
        let test = mockctx_log(&ctx, vec![]);
        assert_eq!(test.unwrap(), ValkeyValue::SimpleStringStatic("OK"));
    }

    #[test]
    fn test_hello() {
        let mut ctx = MockContext::new();
        expect_create_string(&mut ctx, b"Hello, Alice!");
        let args = vec![
            ValkeyString::create_for_test("mockctx.hello"),
            ValkeyString::create_for_test("Alice"),
        ];
        let test = mockctx_hello(&ctx, args).unwrap();
        assert_eq!(
            test,
            ValkeyValue::BulkValkeyString(ValkeyString::create_for_test("Hello, Alice!"))
        );
    }

    #[test]
    fn test_config_get() {
        let mut ctx = MockContext::new();
        ctx.expect_config_get()
            .with(eq("maxmemory"))
            .times(1)
            .returning(|_| Ok(ValkeyString::create_for_test("1073741824")));
        ctx.expect_config_get()
            .with(eq("nonexistent"))
            .times(1)
            .returning(|_| Err(ValkeyError::Str("Unexpected CONFIG GET response")));

        let ok = ctx.config_get("maxmemory").unwrap();
        assert_eq!(ok.as_slice(), b"1073741824");

        let err = ctx.config_get("nonexistent").unwrap_err();
        assert!(matches!(
            err,
            ValkeyError::Str("Unexpected CONFIG GET response")
        ));
    }

    #[test]
    fn test_hello_default_name() {
        let mut ctx = MockContext::new();
        expect_create_string(&mut ctx, b"Hello, World!");
        let args = vec![ValkeyString::create_for_test("mockctx.hello")];
        let test = mockctx_hello(&ctx, args).unwrap();
        assert_eq!(
            test,
            ValkeyValue::BulkValkeyString(ValkeyString::create_for_test("Hello, World!"))
        );
    }
}
