//! Mockable trait abstraction over [`Context`].
//!
//! [`ContextTrait`] mirrors a subset of `Context`'s methods so that command
//! handlers can be written generically (`fn handler(ctx: &impl ContextTrait, ...)`)
//! and unit-tested with [`MockContext`] — generated by `mockall` — instead of
//! requiring a running Valkey server.
//!
//! The mock is only exposed under `cfg(test)` or when the `test-mocks` feature
//! is enabled, so downstream release builds do not pull in `mockall`.

mod context_impl;
mod context_trait;

pub use self::context_trait::ContextTrait;
#[cfg(any(test, feature = "test-mocks"))]
pub use self::context_trait::MockContextTrait as MockContext;
